name: Go

on: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
  push:
    branches: 
      - main
      - dev
      - test
      - 'releases/**'   # Push events to branches matching releases/10,releases/8
#  pull_request:
#    branches: [ main ]
    tags:
      - v1      # Push events to v1 tag
      - V1.*    # Push events to v1.0, v1.1, and v1.9 tags

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build testproject

#    - name: Test
#      run: go test testproject
