name: learn-github-actions
on:   # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
  push:
    branches:
      - main
      - dev
      - test
      - 'releases/**'   # Push events to branches matching releases/10,releases/8,
    tags:
      - v1      # Push events to v1 tag
      - V1.*    # Push events to v1.0, v1.1, and v1.9 tags
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v